/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalUpdateRouteImport } from './routes/portal.update'
import { Route as PortalQuerySingleRouteImport } from './routes/portal.query.single'
import { Route as PortalQueryOverallRouteImport } from './routes/portal.query.overall'
import { Route as PortalQueryEventsRouteImport } from './routes/portal.query.events'
import { Route as PortalAddEventsRouteImport } from './routes/portal.add.events'
import { Route as PortalAddEmployeesRouteImport } from './routes/portal.add.employees'
import { Route as PortalAddDepartmentsRouteImport } from './routes/portal.add.departments'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalUpdateRoute = PortalUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQuerySingleRoute = PortalQuerySingleRouteImport.update({
  id: '/query/single',
  path: '/query/single',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQueryOverallRoute = PortalQueryOverallRouteImport.update({
  id: '/query/overall',
  path: '/query/overall',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQueryEventsRoute = PortalQueryEventsRouteImport.update({
  id: '/query/events',
  path: '/query/events',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAddEventsRoute = PortalAddEventsRouteImport.update({
  id: '/add/events',
  path: '/add/events',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAddEmployeesRoute = PortalAddEmployeesRouteImport.update({
  id: '/add/employees',
  path: '/add/employees',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAddDepartmentsRoute = PortalAddDepartmentsRouteImport.update({
  id: '/add/departments',
  path: '/add/departments',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/update': typeof PortalUpdateRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/add/departments': typeof PortalAddDepartmentsRoute
  '/portal/add/employees': typeof PortalAddEmployeesRoute
  '/portal/add/events': typeof PortalAddEventsRoute
  '/portal/query/events': typeof PortalQueryEventsRoute
  '/portal/query/overall': typeof PortalQueryOverallRoute
  '/portal/query/single': typeof PortalQuerySingleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal/update': typeof PortalUpdateRoute
  '/portal': typeof PortalIndexRoute
  '/portal/add/departments': typeof PortalAddDepartmentsRoute
  '/portal/add/employees': typeof PortalAddEmployeesRoute
  '/portal/add/events': typeof PortalAddEventsRoute
  '/portal/query/events': typeof PortalQueryEventsRoute
  '/portal/query/overall': typeof PortalQueryOverallRoute
  '/portal/query/single': typeof PortalQuerySingleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/update': typeof PortalUpdateRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/add/departments': typeof PortalAddDepartmentsRoute
  '/portal/add/employees': typeof PortalAddEmployeesRoute
  '/portal/add/events': typeof PortalAddEventsRoute
  '/portal/query/events': typeof PortalQueryEventsRoute
  '/portal/query/overall': typeof PortalQueryOverallRoute
  '/portal/query/single': typeof PortalQuerySingleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/portal/update'
    | '/portal/'
    | '/portal/add/departments'
    | '/portal/add/employees'
    | '/portal/add/events'
    | '/portal/query/events'
    | '/portal/query/overall'
    | '/portal/query/single'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal/update'
    | '/portal'
    | '/portal/add/departments'
    | '/portal/add/employees'
    | '/portal/add/events'
    | '/portal/query/events'
    | '/portal/query/overall'
    | '/portal/query/single'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/portal/update'
    | '/portal/'
    | '/portal/add/departments'
    | '/portal/add/employees'
    | '/portal/add/events'
    | '/portal/query/events'
    | '/portal/query/overall'
    | '/portal/query/single'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/update': {
      id: '/portal/update'
      path: '/update'
      fullPath: '/portal/update'
      preLoaderRoute: typeof PortalUpdateRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/query/single': {
      id: '/portal/query/single'
      path: '/query/single'
      fullPath: '/portal/query/single'
      preLoaderRoute: typeof PortalQuerySingleRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/query/overall': {
      id: '/portal/query/overall'
      path: '/query/overall'
      fullPath: '/portal/query/overall'
      preLoaderRoute: typeof PortalQueryOverallRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/query/events': {
      id: '/portal/query/events'
      path: '/query/events'
      fullPath: '/portal/query/events'
      preLoaderRoute: typeof PortalQueryEventsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/add/events': {
      id: '/portal/add/events'
      path: '/add/events'
      fullPath: '/portal/add/events'
      preLoaderRoute: typeof PortalAddEventsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/add/employees': {
      id: '/portal/add/employees'
      path: '/add/employees'
      fullPath: '/portal/add/employees'
      preLoaderRoute: typeof PortalAddEmployeesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/add/departments': {
      id: '/portal/add/departments'
      path: '/add/departments'
      fullPath: '/portal/add/departments'
      preLoaderRoute: typeof PortalAddDepartmentsRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalUpdateRoute: typeof PortalUpdateRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalAddDepartmentsRoute: typeof PortalAddDepartmentsRoute
  PortalAddEmployeesRoute: typeof PortalAddEmployeesRoute
  PortalAddEventsRoute: typeof PortalAddEventsRoute
  PortalQueryEventsRoute: typeof PortalQueryEventsRoute
  PortalQueryOverallRoute: typeof PortalQueryOverallRoute
  PortalQuerySingleRoute: typeof PortalQuerySingleRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalUpdateRoute: PortalUpdateRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalAddDepartmentsRoute: PortalAddDepartmentsRoute,
  PortalAddEmployeesRoute: PortalAddEmployeesRoute,
  PortalAddEventsRoute: PortalAddEventsRoute,
  PortalQueryEventsRoute: PortalQueryEventsRoute,
  PortalQueryOverallRoute: PortalQueryOverallRoute,
  PortalQuerySingleRoute: PortalQuerySingleRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
